// src/common/Navbar.tsx
import { useEffect, useState } from "react";
import { Link, NavLink } from "react-router-dom";
import { V0_BASE_URL } from "../constants";

const navbarLinks = [
  {
    title: "Destinations",
    to: "/trips",
  },
  {
    title: "Gallery",
    to: `${V0_BASE_URL}/gallery`,
  },
  {
    title: "Contact Us",
    to: `${V0_BASE_URL}/contact`,
  },
  {
    title: "Collaborate",
    to: "/collaborate",
  },
  {
    title: "About Us",
    to: "/about"
  }
];

export default function Navbar() {
  const [isNavFixed, setIsNavFixed] = useState(false);

  function checkNavFix() {
    if (window.scrollY > 32) {
      setIsNavFixed(true);
    } else {
      setIsNavFixed(false);
    }
  }

  useEffect(() => {
    window.addEventListener("scroll", () => {
      checkNavFix();
    });
    checkNavFix();
  }, []);

  return (
    <>
      <nav
        className={`fixed top-0 left-0 w-screen p-page py-7 flex justify-between items-center z-[100] duration-500 border-b
      ${isNavFixed ? "bg-background border-front" : "bg-transparent border-back"
          }`}
      >
        <Link to="/">
          <img
            src="/header.webp"
            alt="shantitrip logo"
            className={`h-14 duration-500 ${isNavFixed ? "" : "brightness-0 invert"
              }`}
          />
        </Link>
        <div className="flex gap-x-8 items-center">
          {navbarLinks.map((item) => (
            <NavLink
              key={item.title}
              to={item.to}
              className={({ isActive, isPending }) =>
                `duration-500 ${isNavFixed ? "text-front" : "text-back"} ${isPending
                  ? "cursor-not-allowed text-opacity-40"
                  : isActive
                    ? "text-primary brightness-150 pointer-events-none"
                    : "hover:text-primary hover:saturate-200"
                }`
              }
            >
              {item.title}
            </NavLink>
          ))}
          <button className="btn-1">
            Login
            <span className="material-icons">&#xea77;</span>
          </button>
        </div>
      </nav>
    </>
  );
}

// components/Navbar.vue
<template>
  <header class="fixed z-50 mobile:bottom-0">
    <nav class="navbar flex flex-row justify-between p-page py-4 w-screen widescreen-only">
      <div class="navbar-branding left">
        <NuxtLink to="/">
          <img
            src="/header.webp"
            class="h-12"
            id="header-logo"
            alt="ShantiTrip Holidays logo"
          />
        </NuxtLink>
      </div>
      <div class="right">
        <ul class="navbar-items flex flex-row items-center h-full gap-12">
          <li class="navbar-item">
            <NuxtLink to="/">Home</NuxtLink>
          </li>
          <li class="navbar-item">
            <NuxtLink to="/about">About</NuxtLink>
          </li>
          <li class="navbar-item">
            <NuxtLink to="/trips">Trips</NuxtLink>
          </li>
          <li class="navbar-item">
            <NuxtLink to="/destinations">Destinations</NuxtLink>
          </li>
          <li class="navbar-item">
            <NuxtLink to="/contact">Contact</NuxtLink>
          </li>
          <li class="navbar-item">
            <NuxtLink to="/agents">Collaborate</NuxtLink>
          </li>
        </ul>
      </div>
    </nav>
    <nav class="mobile-only mobile-navbar"></nav>
  </header>
</template>

<script setup>
const noFixPages = ["destinations"];

onMounted(() => {
  const navbar = document.querySelector(".navbar");
  const fixNavbar = () => {
    if (window.scrollY > 49) {
      let { name: routeName } = useRoute();
      if (!noFixPages.includes(routeName)) {
        navbar.classList.add("nav-fix");
      }
    } else {
      navbar.classList.remove("nav-fix");
    }
  };
  window.addEventListener("scroll", fixNavbar);
});
</script>

<style scoped>
.navbar {
  transition: 300ms ease;
}
.navbar:not(.nav-fix) {
  background-color: transparent;
  padding-bottom: 8vh;
  margin-bottom: -6vh;
}
.navbar.nav-fix {
  background-color: rgba(var(--background));
  box-shadow: 0px -2px 6px rgb(var(--text-primary));
}
.navbar-item {
  font-size: 1.2rem;
}
.navbar:not(.nav-fix) .navbar-branding {
  filter: brightness(0) invert(1);
}
.navbar:not(.nav-fix) .navbar-item a {
  color: rgb(var(--text-secondary));
}
.navbar.nav-fix .navbar-branding {
  filter: brightness(1) invert(0);
}
.navbar.nav-fix .navbar-item a {
  color: rgb(var(--text-primary));
}
.navbar .navbar-item a:hover {
  color: rgb(var(--primary));
  transition: 300ms;
}
.navbar-item:has(.router-link-exact-active) {
  display: none;
}
</style>
