// components/Footer.vue
<template>
  <footer class="p-page pb-5 bg-foreground mt-60">
    <div class="CTA-block bg-background w-max p-8 mx-auto rounded-md">
      <h2 class="text-3xl font-bold text-center">
        Feeling <span class="color-primary">Left</span> Out?
      </h2>
      <p class="my-5 italic opacity-80">
        Every once in a while, we send out a newsletter featuring the latest and
        best in travel. Subscribe to never miss out.
      </p>
      <div class="flex flex-row justify-evenly h-10">
        <input
          type="email"
          class="border-2 border-solid border-[rgb(var(--foreground))] rounded-md px-2 basis-[73%]"
          placeholder="Enter your email"
          autocomplete="email"
        />
        <button
          class="btn-secondary m-0 px-2 py-0 border-2 border-solid border-[rgb(var(--primary))] basis-[20%]"
        >
          Subscribe
        </button>
      </div>
    </div>
    <div class="w-max">
      <NuxtLink to="/">
        <img
          src="/header.png"
          class="footer-branding h-20 invert brightness-0"
          alt="shantitrip-flat-logo"
        />
      </NuxtLink>
    </div>
    <div class="content flex flex-col text-secondary">
      <p class="text-3xl opacity-60 mt-2 self-center">Useful Links</p>
      <div class="links flex flex-row justify-evenly mt-8">
        <div class="flex flex-col">
          <NuxtLink to="terms-and-conditions">Terms & Conditions</NuxtLink>
          <NuxtLink to="privacy-policy">Privacy Policy</NuxtLink>
          <NuxtLink to="cookie-policy">Cookie Policy</NuxtLink>
        </div>
        <div class="flex flex-col">
          <NuxtLink to="destinations">Destinations</NuxtLink>
          <NuxtLink to="trips">Trips</NuxtLink>
        </div>
        <div class="flex flex-col">
          <NuxtLink to="/">Home</NuxtLink>
          <NuxtLink to="/about">About Us</NuxtLink>
          <NuxtLink to="/help">Help</NuxtLink>
        </div>
        <div class="flex flex-col">
          <NuxtLink to="/contact">Contact Us</NuxtLink>
          <NuxtLink to="/agents">Partner with us</NuxtLink>
          <NuxtLink to="/contact">Support</NuxtLink>
        </div>
      </div>
      <hr class="my-5" />
      <p class="self-center text-sm opacity-80 cursor-default">
        © 2023 ShantiTrip All rights reserved.
      </p>
    </div>
  </footer>
</template>

<script setup></script>

<style scoped>
.CTA-block {
  box-shadow: 0px 0px 5px rgb(var(--text-primary), 0.38);
  transform: translateY(-50%);
}
.links a {
  @apply font-light text-secondary my-1 hover:opacity-75 hover:underline;
  transition: 200ms;
}
</style>

// src/common/Footer.tsx
import { Link } from "react-router-dom";

const socials = [
  {
    name: "instagram",
    link: "https://www.instagram.com/shantitripholidays",
    icon: "/icons/instagram.svg",
  },
  {
    name: "twitter",
    link: "https://www.instagram.com/shantitripholidays",
    icon: "/icons/twitter.svg",
  },
  {
    name: "facebook",
    link: "https://www.instagram.com/shantitripholidays",
    icon: "/icons/facebook.svg",
  },
];

const usefulLinks = [
  [
    { title: "Destinations", link: "/" },
    { title: "Gallery", link: "/" },
    { title: "Contact Us", link: "/" },
    { title: "Collaborate", link: "/" },
  ],
  [
    { title: "Terms & Conditions", link: "/" },
    { title: "Privacy Policy", link: "/" },
    { title: "Cookie Policy", link: "/" },
  ],
  [
    { title: "Help", link: "/" },
    { title: "Support", link: "/" },
    { title: "Partner with us", link: "/" },
  ],
];

export default function Footer() {
  return (
    <>
      <div className="p-page relative">
        <div
          className="flex flex-col items-center translate-y-32 bg-background rounded-lg"
          style={{ boxShadow: "8px 5px 16px #00000038" }}
        >
          <img
            src="/images/paper-plane-with-dotted-line.png"
            alt="paper plane"
            draggable={false}
          />
          <div className="flex flex-col gap-y-5 text-center">
            <h2 className="text-4xl font-light text-primary">
              Feeling Left Out?
            </h2>
            <p className="text-sm">
              Every once in a while, we send out a newsletter featuring the
              latest and best in travel. Subscribe to never miss out.
            </p>
          </div>
          <div className="w-1/2 relative flex">
            <input
              type="text"
              placeholder="Enter your email"
              className="p-3 my-6 w-full border border-front rounded-full border-opacity-60 text-opacity-50"
            />
            <button className="absolute right-1 top-1/2 -translate-y-1/2 btn-1">
              Subscribe
            </button>
          </div>
        </div>
      </div>
      <footer className="pt-44 pb-6 p-page bg-primary flex text-back justify-between">
        <div className="flex flex-col gap-y-5 items-baseline basis-2/5">
          <Link to="/" draggable={false}>
            <img
              src="/header.webp"
              alt="shantitrip logo"
              className="brightness-0 invert h-14"
              draggable={false}
            />
          </Link>
          <p className="">
            Lorem ipsum dolor sit amet. 33 nulla odit aut quia fugit in culpa
            voluptatem sit esse quasi. Qui distinctio cupiditate sit tempora
            exercitationem et ducimus internos sed perspiciatis expedita eos
            porro dolorem.
          </p>
          <div className="flex text-lg font-light gap-x-3 items-center  ">
            Follow us on
            {socials.map((social) => (
              <div className="rounded-full bg-background flex justify-center items-center w-14 h-14">
                <img src={social.icon} alt={social.name} />
              </div>
            ))}
          </div>
        </div>
        <div className="basis-2/5">
          <h2 className="text-2xl font-light py-4">Useful Links</h2>
          <div className="flex justify-between">
            {usefulLinks.map((sect) => (
              <div className="flex flex-col gap-y-2">
                {sect.map((link) => (
                  <Link className="font-semibold text-sm" to={link.link}>
                    {link.title}
                  </Link>
                ))}
              </div>
            ))}
          </div>
        </div>
      </footer>
      <div className="w-full text-center text-xs py-2 border-t bg-primary border-back border-opacity-40 text-back">
        © ShantiTrip. All Rights Reserved 2023.
      </div>
    </>
  );
}
